# Generated by Django 5.1.3 on 2024-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Kelas 1', 'Kelas 1'), ('Executive', 'Executive'), ('VIP', 'VIP')], max_length=50)),
                ('bed', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('food_service', models.CharField(max_length=255)),
            ],
        ),
    ]
