# Generated by Django 5.1.3 on 2024-11-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfacility',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='roomfacility',
            name='food_service',
        ),
        migrations.AddField(
            model_name='roomfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='roomfacility',
            name='features',
            field=models.TextField(help_text='Masukkan fitur, pisahkan dengan koma (contoh: AC, TV LED, Wi-Fi gratis)'),
        ),
    ]
